services:
  print:
    image: camptocamp/mapfish_print:latest
    ports:
      - "8080:8080"
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/print/apps.json > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 20

  client:
    image: curlimages/curl:latest
    user: "0:0"
    depends_on:
      print:
        condition: service_healthy
    volumes:
      - ./request.json:/workspace/request.json:ro
      - ./out:/out
    command:
      - sh
      - -c
      - >-
        until curl -sf http://print:8080/print/apps.json > /dev/null; do echo waiting for print; sleep 2; done; mkdir -p /out && chmod 777 /out && curl -f -sS -X POST -H 'Content-Type: application/json' --data @/workspace/request.json http://print:8080/print/report.pdf


