version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  print:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
